// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package dbsql

import (
	"database/sql"
)

type Divisao struct {
	Nome      string
	Cidade    string
	IDDivisao int64
	Descricao sql.NullString
}

type Empregador struct {
	ID          int64
	Nome        sql.NullString
	Responsavel sql.NullString
	Telefone    sql.NullString
	Abreviacao  sql.NullString
	Divisao     sql.NullInt32
}
